version: '3'

services:
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass requirePassword
    ports:
      - '6379:6379'

  postgres:
    image: 'postgres:11.8-alpine'
    environment:
      POSTGRES_DB: resonate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'

  backend-rsnt:
    build:
      context: ./backend-rsnt/
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend-rsnt:/home/app
    env_file: ./backend-rsnt/.env.compose
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres

  frontend-rsnt:
    build:
      context: ./frontend-rsnt/
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend-rsnt:/home/app
    env_file: ./frontend-rsnt/.env.compose
    ports:
      - '3001:3001'
    stdin_open: true
