version: '3'

services:
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass requirePassword
    ports:
      - '6379:6379'

  postgres:
    image: 'postgres:11.8-alpine'
    environment:
      POSTGRES_DB: resonate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'

  backend-sb:
    build:
      context: ./backend-sb/
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend-sb:/home/app
    env_file: ./backend-sb/.env.compose
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres

  frontend-sb:
    build:
      context: ./frontend-sb/
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend-sb:/home/app
    env_file: ./frontend-sb/.env.compose
    ports:
      - '3001:3001'
    stdin_open: true
